name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build minio server
      working-directory: ./minio
      run: docker-compose up -d
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
